spring:
  application:
    name: estacionamento
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/estacionamento
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
